// ! SPLICE
/* 
3 KAAM KRTA HAI
1-> ADD KRNA
2-> DELETE KRNA
3-> REPLACE KRNA
? OR KHIN SE BHI KR SKTA HAI
? YE RETURN MEN DELETED ELEMENTS DETA HAI
*/
// !TYPES OF METHODS
/*
THERE ARE 3 TYPES OF METHODS
1-> WO METHOD JO GLOBALLY AVAILABLE HOTE HEN. JESE ALERT() , PROMPT()
2-> KUCH HOTE HEN JO KISI K SAATH ATTACH HOTE HEN WO USI K SAATH HI MILTE HEN JESE K 'ARRAY K METHODS' ARRAY K SAATH HI MILENGE OTHERWISE NHI MILGENE.
3-> WO METHODS JO HAM KHUD BANATE HEN
*/

// !LOOP
/*
Q -> WHY DO WE USE LOOP
 1-> ITERATION K LYE
 2-> SEARCHING K LYE
 
 
? HOW TO PRACTICE LOOP
1 - PAHARE PRINT KRO 2 K
2 - USER SE POOCHO K KONSA PAHARA PRINT KRNA HAI
3 - USER SE POOCHO KHAN TAK PRINT KRWANA HAI
4 - ARRAY KO PRINT KRWANA LENGTH K ZARIE SE
5 - LENGTH KO SAMAJHNA
6 - USER KO FIND KRNA HAI ARRAY MEN SE 
7 - FLAG KA USE KRNA HAI
8 - BREAK KA KEYWORD 
9 - NESTED LOOP
10 - NESTED LOOP CHALA K i , j KO CONSOLE KR K RESULT CHECK KRO 
11 - ARRAY MEN SE DUPLICATE VLAUES KO DELETE KRNA HAI 
12 - INDEX OF PARNA HAI
13 - PALINDROM WORDS KO CHECK KRNA HAI WO WORD JO ULTA KRNE PER BHI SAME REHTE HEN
*/

// var userInput = prompt("Enter your value");
// var flag = false;
// var searchedName = "";
// var nameIndex = 0;
// const arr = [
//   "Ahmed",
//   "Fatima",
//   "Ali",
//   "Ayesha",
//   "Hassan",
//   "Zainab",
//   "Umar",
//   "Khadija",
//   "Bilal",
//   "Hafsa",
// ];
// for (var i = 0; i < arr.length; i++) {
//   console.log("i ki value =>", i);
//   if (userInput == arr[i]) {
//     flag = true;
//     searchedName = arr[i];
//     nameIndex = i + 1;
//     break;
//   }
// }
// if (flag) {
//   console.log("Hi", searchedName, "kese ho apka", nameIndex, "number hai");
// } else {
//   console.log("sorry");
// }
// console.log("MEN BAAD MEN LIKHA HUWA HUN", arr.length);
const arr = [
  "Ahmed",
  "Fatima",
  "Ali",
  "Ayesha",
  "Hassan",
  "Fatima",
  "Zainab",
  "Hafsa",
  "Umar",
  "Khadija",
  "Bilal",
  "Khadija",
  "Ali",
  "Ahmed",
  "Hafsa",
];
for (var i = 1; i <= 5; i++) {
  for (var j = i; j <= 5; j++) {
    console.log(i, j);
  }
}

// ! CHANGING CASES OF STRING
/*
Q => WHY DO WE CHANGE THE CASE OF STRING
A => ISKI ZARURAT YE HAI K AP NE APNI APP MEN JIS CASE KO FOLLOW KYA HIA FOR EXAMPLE LOWERCASE KO TO USER K INPUT KO AP USE CASE MEN CHANGE KR SKEN CHAHE USER KISI BHI CASE MEN DATA DE.
FOR EXAMPLE-> AGAR USER CAMPLE CASE MEN, CAPITAL LETTERS MEN, YA AIK LETTER BARA AIK CHOTA KR K INPUT KRE TO AP USKE INPUT KO APNE HISAB SE CHANGE KR SKTE HEN CHAEHN TO SAB KO UPPERCASE MEN CONVERT KR DEN YA LOWERCASE MEN KR DEN APKI MARZI HAI.

?NOTE => YE METHODS RETURN MEN UPDATED VALUE DETE HEN ORIGINAL VALUE KO KUCH NHI KRTE
*/

//! FINDING SEGMENT
/*
1 ==> INDEXOFZ()
YE ARRAY OR STRING DONO PER CHALTA HAI
YE VALUE MILNE PER USKA INDEX RETURN KRTA HAI
OR VALUE NA MILNE PER YE -1 RETURN KRTA HAI.


2 ==> LASTINDEXOF()
YE BHI INDEXOF KI TARAH HAI BAS YE LAST MEN SE VALUE KO DHOONDHTA HAI
OR YE BHI RETURN MEN VALUE KA INDEX RETURN KRTA HAI.
*/

//! REPLACING CHARACTORS
/*
LOOP K ZARIE WORD KO DHOONDHNA HAI STRING MEN SE
USE REPLACE KRNA HAI NEW WORD SE
*/

//! RANDOM NUMBERS
/*
MATH.RANDOM()
1=> PASSWORD GENERATOR
2=> HEAD TAILS

PARSINT && PARSEFLOAT
IN MEN DIFFERENCE YE HAI K PARSEINT STRING MEN MOJOOD DECIMALS KO REMOVE KR K JUST INTEGER KO RETURN KRTA HAI NUMBER MEN CONVERT KR K.
OR PARSEFLOAT AS IT IS WITH DECIMALS STRING KO NUMBERS MEN CONVERT KRTA HAI.
*/

//! WEBSITES TO PRACTICE
/*
1=> FREE CODE CAMP
2=> LEET CODE
3=> HACKER RANK

*/
